// database.js — stable facade over the domain modules in ./db/.
// The public surface is exactly the one the original monolith exported.
const catalog = require('./db/catalog');
const core = require('./db/core');
const invoices = require('./db/invoices');
const returns = require('./db/returns');
const users = require('./db/users');
const cash = require('./db/cash');
const payments = require('./db/payments');
const parties = require('./db/parties');
const settings = require('./db/settings');
const reports = require('./db/reports');

module.exports = {
  adjustProductStock: catalog.adjustProductStock,
  auditLog: core.auditLog,
  beginWindowsHelloAuthentication: users.beginWindowsHelloAuthentication,
  beginWindowsHelloRegistration: users.beginWindowsHelloRegistration,
  cancelInvoice: invoices.cancelInvoice,
  cancelInvoice: invoices.cancelInvoice,
  cancelPurchaseReturn: returns.cancelPurchaseReturn,
  cancelSaleReturn: returns.cancelSaleReturn,
  changeCurrentUserPassword: users.changeCurrentUserPassword,
  checkProductDuplicate: catalog.checkProductDuplicate,
  closeDailyAccount: cash.closeDailyAccount,
  clearQuickPin: users.clearQuickPin,
  closeDatabase: core.closeDatabase,
  createCashTransaction: cash.createCashTransaction,
  createCategory: catalog.createCategory,
  createInstallmentPlan: payments.createInstallmentPlan,
  createParty: parties.createParty,
  createProduct: catalog.createProduct,
  createPurchase: invoices.createPurchase,
  createPurchaseReturn: returns.createPurchaseReturn,
  createSale: invoices.createSale,
  createSaleReturn: returns.createSaleReturn,
  createUnit: catalog.createUnit,
  createUser: users.createUser,
  finishWindowsHelloAuthentication: users.finishWindowsHelloAuthentication,
  finishWindowsHelloRegistration: users.finishWindowsHelloRegistration,
  getAppSettings: settings.getAppSettings,
  getCashSummary: cash.getCashSummary,
  getCashTransaction: cash.getCashTransaction,
  getCurrencyInputFactor: settings.getCurrencyInputFactor,
  getCurrentUser: core.getCurrentUser,
  getDailyClosure: cash.getDailyClosure,
  getDashboardSummary: reports.getDashboardSummary,
  getDatabase: core.getDatabase,
  getQuickPinStatus: users.getQuickPinStatus,
  getInvoiceDetails: invoices.getInvoiceDetails,
  getNextInvoiceNumber: invoices.getNextInvoiceNumber,
  getNextProductCode: catalog.getNextProductCode,
  getPartyLedger: parties.getPartyLedger,
  getProduct: catalog.getProduct,
  getProfitLossReport: reports.getProfitLossReport,
  getPurchasePriceHistory: invoices.getPurchasePriceHistory,
  getPurchaseReturnDetails: returns.getPurchaseReturnDetails,
  getSaleReturnDetails: returns.getSaleReturnDetails,
  getSalesReport: reports.getSalesReport,
  getSalesForecast: reports.getSalesForecast,
  hashPassword: core.hashPassword,
  importProducts: catalog.importProducts,
  listAuditLogs: users.listAuditLogs,
  listCashTransactions: cash.listCashTransactions,
  listCategories: catalog.listCategories,
  listChecks: payments.listChecks,
  listDailyClosures: cash.listDailyClosures,
  listInstallmentPlans: payments.listInstallmentPlans,
  listNotifications: reports.listNotifications,
  listParties: parties.listParties,
  listProducts: catalog.listProducts,
  listPurchaseReturns: returns.listPurchaseReturns,
  listPurchases: invoices.listPurchases,
  listSales: invoices.listSales,
  listSalesReturns: returns.listSalesReturns,
  listStockMovements: catalog.listStockMovements,
  listUnits: catalog.listUnits,
  listUsers: users.listUsers,
  loginUser: users.loginUser,
  logoutUser: users.logoutUser,
  mergeDailySales: invoices.mergeDailySales,
  previewProductImport: catalog.previewProductImport,
  recordInstallmentPayment: payments.recordInstallmentPayment,
  requireDatabase: core.requireDatabase,
  requirePermission: core.requirePermission,
  resetAdminPassword: users.resetAdminPassword,
  runInTransaction: core.runInTransaction,
  saveAppSettings: settings.saveAppSettings,
  searchCustomers: parties.searchCustomers,
  searchProducts: catalog.searchProducts,
  setCategoryActive: catalog.setCategoryActive,
  setCurrentUser: core.setCurrentUser,
  setPartyActive: parties.setPartyActive,
  setProductActive: catalog.setProductActive,
  setSalePinned: invoices.setSalePinned,
  setQuickPin: users.setQuickPin,
  setUnitActive: catalog.setUnitActive,
  setUserActive: users.setUserActive,
  settleInvoice: invoices.settleInvoice,
  updateCategory: catalog.updateCategory,
  updateCheckStatus: payments.updateCheckStatus,
  updateParty: parties.updateParty,
  updateProduct: catalog.updateProduct,
  updateProductQuick: catalog.updateProductQuick,
  updateSale: invoices.updateSale,
  updateUnit: catalog.updateUnit,
  unlockWithQuickPin: users.unlockWithQuickPin,
  userUsesDefaultPassword: users.userUsesDefaultPassword,
};
